### PR TITLE
Vamshi sensor libs

### PR DESCRIPTION
**Pull request by fazerlicourice7**
Create libraries for all some sensors, and solenoid actuation. 
Simplify usage in Client/Brain code.
By calling a function of the form `get<data>(float *data)`  where `<data>` can be replaced by `Temperature`, `Pressure`, etc.

### CODE REVIEW

**Comment by fazerlicourice7** [comment]
We might want to move this into the Common repository we used to have, but I'm just putting it here now.

**Comment by vainaviv** [comment]
Everything looks good! Just wanted to confirm, I didn't see any read data function in solenoids. Is that still in progress or is that just something we won't be collecting data for? Also just checking, nothing in ducers yet, right?

**Comment by fazerlicourice7** [comment]
Correct, ducers is still WIP, just wanted to get merged in prior to this weekend. 
And solenoids are the actuators, so outputs, not inputs.

**Comment by fazerlicourice7** [comment]
And you should add a review in the top right, and approve it

**Review by vainaviv — APPROVED** [review]
Looks good! I approve 👍

**Pull request merged**
